CREATE TABLE `lifecycle_snapshots` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `serviceType` VARCHAR(20) NOT NULL,
  `bookingId` INTEGER NOT NULL,
  `bookingStage` VARCHAR(30) NOT NULL,
  `paymentStage` VARCHAR(30) NOT NULL,
  `receiptStage` VARCHAR(30) NOT NULL,
  `responsibilityStage` VARCHAR(30) NOT NULL,
  `caseStage` VARCHAR(30) NOT NULL,
  `requiredAction` VARCHAR(40) NOT NULL,
  `consistencyStatus` VARCHAR(20) NOT NULL,
  `issueFingerprint` VARCHAR(128) NULL,
  `issues` JSON NULL,
  `calculatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `lifecycle_snapshots_serviceType_bookingId_key`(`serviceType`, `bookingId`),
  INDEX `lifecycle_snapshots_consistencyStatus_calculatedAt_idx`(`consistencyStatus`, `calculatedAt`),
  INDEX `lifecycle_snapshots_serviceType_calculatedAt_idx`(`serviceType`, `calculatedAt`),
  INDEX `lifecycle_snapshots_requiredAction_calculatedAt_idx`(`requiredAction`, `calculatedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `lifecycle_exceptions` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `serviceType` VARCHAR(20) NOT NULL,
  `bookingId` INTEGER NOT NULL,
  `code` VARCHAR(80) NOT NULL,
  `severity` VARCHAR(20) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  `fingerprint` VARCHAR(128) NOT NULL,
  `message` TEXT NOT NULL,
  `metadata` JSON NULL,
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `acknowledgedAt` DATETIME(3) NULL,
  `resolvedAt` DATETIME(3) NULL,
  `ignoredAt` DATETIME(3) NULL,
  `acknowledgedBy` INTEGER NULL,
  `resolvedBy` INTEGER NULL,
  `ignoredBy` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `lifecycle_exceptions_serviceType_bookingId_fingerprint_key`(`serviceType`, `bookingId`, `fingerprint`),
  INDEX `lifecycle_exceptions_status_severity_lastSeenAt_idx`(`status`, `severity`, `lastSeenAt`),
  INDEX `lifecycle_exceptions_serviceType_bookingId_idx`(`serviceType`, `bookingId`),
  INDEX `lifecycle_exceptions_code_status_idx`(`code`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
