import type { MetadataRoute } from "next";

export const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://nolsaf.com";

export const seoKeywords = [
  "NoLSAF",
  "NoLSAF Tanzania",
  "tourism in Tanzania",
  "tourism in Africa",
  "tourism in East Africa",
  "Tanzania travel",
  "East Africa travel",
  "Africa travel platform",
  "verified accommodation Tanzania",
  "verified hotels Tanzania",
  "hotel booking Tanzania",
  "Dar es Salaam hotels",
  "Zanzibar accommodation",
  "Arusha accommodation",
  "Serengeti safari",
  "Ngorongoro safari",
  "Mount Kilimanjaro travel",
  "Tanzania safari packages",
  "East Africa tour packages",
  "Africa tour operators",
  "airport transfer Tanzania",
  "driver transport Tanzania",
  "group stays Tanzania",
  "travel cost estimator Tanzania",
  "NoLScope trip estimator",
  "custom trip planning Tanzania",
  "safe travel Tanzania",
  "verified property booking Africa",
  "local tourism Tanzania",
  "cultural tours Tanzania",
  "beach holidays Zanzibar",
  "business travel Tanzania",
  "family accommodation Tanzania",
  "M-Pesa travel payments",
  "Airtel Money booking",
  "Mixx by Yas travel payments",
  "bank transfer Tanzania travel",
  "card payments Tanzania",
  "mobile money tourism Tanzania",
];

export const publicSeoRoutes: MetadataRoute.Sitemap = [
  { url: `${SITE_URL}/`, lastModified: new Date(), changeFrequency: "daily", priority: 1.0 },
  { url: `${SITE_URL}/public`, lastModified: new Date(), changeFrequency: "daily", priority: 1.0 },
  { url: `${SITE_URL}/public/properties`, lastModified: new Date(), changeFrequency: "hourly", priority: 0.95 },
  { url: `${SITE_URL}/public/tour-packages`, lastModified: new Date(), changeFrequency: "daily", priority: 0.92 },
  { url: `${SITE_URL}/public/tour-packages/operators`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.75 },
  { url: `${SITE_URL}/public/nolscope`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
  { url: `${SITE_URL}/public/group-stays`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.86 },
  { url: `${SITE_URL}/public/countries`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.84 },
  { url: `${SITE_URL}/public/countries/tanzania`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
  { url: `${SITE_URL}/tourism/tanzania`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.98 },
  { url: `${SITE_URL}/tourism/east-africa`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.72 },
  { url: `${SITE_URL}/services/verified-accommodation-tanzania`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.92 },
  { url: `${SITE_URL}/services/tanzania-tour-packages`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
  { url: `${SITE_URL}/services/airport-transfer-tanzania`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.86 },
  { url: `${SITE_URL}/services/group-stays-tanzania`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.84 },
  { url: `${SITE_URL}/services/tanzania-trip-cost-estimator`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.88 },
  { url: `${SITE_URL}/services/payments-tanzania-east-africa`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.82 },
  { url: `${SITE_URL}/nrms`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.88 },
  { url: `${SITE_URL}/help/nrms-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
  { url: `${SITE_URL}/help`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.62 },
  { url: `${SITE_URL}/updates`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.58 },
  { url: `${SITE_URL}/updates/success-stories`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.54 },
  { url: `${SITE_URL}/updates/challenges`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.48 },
  { url: `${SITE_URL}/careers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.45 },
  { url: `${SITE_URL}/terms`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.4 },
  { url: `${SITE_URL}/privacy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.4 },
  { url: `${SITE_URL}/account-deletion`, lastModified: new Date("2026-08-13"), changeFrequency: "yearly", priority: 0.4 },
  { url: `${SITE_URL}/cookies-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.35 },
  { url: `${SITE_URL}/cancellation-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.4 },
  { url: `${SITE_URL}/disbursement-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.35 },
  { url: `${SITE_URL}/verification-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.35 },
  { url: `${SITE_URL}/property-owner-disbursement-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.35 },
  { url: `${SITE_URL}/driver-disbursement-policy`, lastModified: new Date("2026-01-01"), changeFrequency: "yearly", priority: 0.35 },
];

export const destinationSeoRoutes: MetadataRoute.Sitemap = [
  "dar-es-salaam",
  "zanzibar",
  "arusha",
  "serengeti",
  "ngorongoro",
  "kilimanjaro",
  "ruaha",
].map((slug) => ({
  url: `${SITE_URL}/tourism/tanzania/${slug}`,
  lastModified: new Date(),
  changeFrequency: "weekly" as const,
  priority: slug === "zanzibar" || slug === "serengeti" ? 0.94 : 0.88,
}));

export function buildRootJsonLd() {
  const services = [
    "Verified accommodation booking",
    "Hotels, lodges, apartments, villas and guest houses",
    "Tanzania and East Africa tour packages",
    "Airport transfers and driver transport",
    "Group stays and multi-room accommodation",
    "Custom trip planning",
    "NoLScope travel cost estimation",
    "Secure local and international payments through mobile money/MNO, bank transfer and cards",
  ];

  return [
    {
      "@context": "https://schema.org",
      "@type": "TravelAgency",
      "@id": `${SITE_URL}/#organization`,
      name: "NoLSAF",
      legalName: "NoLS Africa Co Ltd",
      url: SITE_URL,
      slogan: "Quality Stay for Every Wallet",
      description:
        "NoLSAF helps travelers discover verified accommodation, tour packages, transport, group stays and travel planning services across Tanzania and East Africa.",
      areaServed: [
        { "@type": "Country", name: "Tanzania" },
        { "@type": "Place", name: "East Africa" },
        { "@type": "Place", name: "Africa" },
      ],
      serviceType: services,
      knowsAbout: seoKeywords,
    },
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      name: "NoLSAF",
      url: SITE_URL,
      publisher: { "@id": `${SITE_URL}/#organization` },
      potentialAction: {
        "@type": "SearchAction",
        target: `${SITE_URL}/public/properties?search={search_term_string}`,
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      "@id": `${SITE_URL}/#services`,
      name: "NoLSAF travel and tourism services",
      itemListElement: services.map((name, index) => ({
        "@type": "ListItem",
        position: index + 1,
        item: {
          "@type": "Service",
          name,
          provider: { "@id": `${SITE_URL}/#organization` },
          areaServed: "Tanzania, East Africa, Africa",
        },
      })),
    },
  ];
}
