-- Correct retention trigger priority and cover work items inserted as resolved.
-- This is forward-only because the original retention migrations are already applied.

DROP TRIGGER IF EXISTS `auditlog_retention_before_insert`;
CREATE TRIGGER `auditlog_retention_before_insert`
BEFORE INSERT ON `auditlog`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`expiresAt` IS NOT NULL
      AND NEW.`retentionClass` IN ('OTP', 'TECHNICAL', 'SECURITY', 'OPERATIONAL', 'FINANCIAL', 'COMPLIANCE')
      THEN NEW.`retentionClass`
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' OR UPPER(NEW.`entity`) LIKE 'OTP:%' THEN 'OTP'
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' OR UPPER(NEW.`entity`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      OR UPPER(NEW.`entity`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      THEN 'FINANCIAL'
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      OR UPPER(NEW.`entity`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      THEN 'TECHNICAL'
    WHEN UPPER(NEW.`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      OR UPPER(NEW.`entity`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = COALESCE(NEW.`expiresAt`, CASE
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' OR UPPER(NEW.`entity`) LIKE 'OTP:%' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 30 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' OR UPPER(NEW.`entity`) REGEXP 'KYC|AML|COMPLIANCE' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      OR UPPER(NEW.`entity`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      OR UPPER(NEW.`entity`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      THEN DATE_ADD(NEW.`createdAt`, INTERVAL 90 DAY)
    ELSE DATE_ADD(NEW.`createdAt`, INTERVAL 2 YEAR)
  END);

DROP TRIGGER IF EXISTS `adminaudit_retention_before_insert`;
CREATE TRIGGER `adminaudit_retention_before_insert`
BEFORE INSERT ON `adminaudit`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`expiresAt` IS NOT NULL
      AND NEW.`retentionClass` IN ('OTP', 'TECHNICAL', 'SECURITY', 'OPERATIONAL', 'FINANCIAL', 'COMPLIANCE')
      THEN NEW.`retentionClass`
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' THEN 'OTP'
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX' THEN 'FINANCIAL'
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC' THEN 'TECHNICAL'
    WHEN UPPER(NEW.`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT' THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = COALESCE(NEW.`expiresAt`, CASE
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 30 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 90 DAY)
    ELSE DATE_ADD(NEW.`createdAt`, INTERVAL 2 YEAR)
  END);

DROP TRIGGER IF EXISTS `admin_work_item_retention_before_insert`;
CREATE TRIGGER `admin_work_item_retention_before_insert`
BEFORE INSERT ON `admin_work_item`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`category` IN ('PAYMENTS', 'CANCELLATIONS') THEN 'FINANCIAL'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = CASE
    WHEN NEW.`status` <> 'RESOLVED' THEN NULL
    WHEN NEW.`expiresAt` IS NOT NULL THEN NEW.`expiresAt`
    WHEN NEW.`category` IN ('PAYMENTS', 'CANCELLATIONS')
      THEN DATE_ADD(COALESCE(NEW.`resolvedAt`, NEW.`createdAt`, CURRENT_TIMESTAMP(3)), INTERVAL 7 YEAR)
    ELSE DATE_ADD(COALESCE(NEW.`resolvedAt`, NEW.`createdAt`, CURRENT_TIMESTAMP(3)), INTERVAL 2 YEAR)
  END;
