-- Tiered audit retention with legal hold protection.
-- Existing evidence is classified before insert triggers begin governing new rows.

ALTER TABLE `auditlog`
  ADD COLUMN `retentionClass` VARCHAR(20) NOT NULL DEFAULT 'OPERATIONAL',
  ADD COLUMN `expiresAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldReason` VARCHAR(500) NULL,
  ADD INDEX `auditlog_expiresAt_legalHoldAt_idx` (`expiresAt`, `legalHoldAt`),
  ADD INDEX `auditlog_retentionClass_expiresAt_idx` (`retentionClass`, `expiresAt`);

UPDATE `auditlog`
SET
  `retentionClass` = CASE
    WHEN UPPER(`action`) LIKE '%OTP%' OR UPPER(`entity`) LIKE 'OTP:%' THEN 'OTP'
    WHEN UPPER(`action`) REGEXP 'KYC|AML|COMPLIANCE' OR UPPER(`entity`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      OR UPPER(`entity`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      THEN 'FINANCIAL'
    WHEN UPPER(`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      OR UPPER(`entity`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      THEN 'TECHNICAL'
    WHEN UPPER(`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      OR UPPER(`entity`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END;

UPDATE `auditlog`
SET `expiresAt` = CASE `retentionClass`
  WHEN 'OTP' THEN DATE_ADD(`createdAt`, INTERVAL 30 DAY)
  WHEN 'TECHNICAL' THEN DATE_ADD(`createdAt`, INTERVAL 90 DAY)
  WHEN 'FINANCIAL' THEN DATE_ADD(`createdAt`, INTERVAL 7 YEAR)
  WHEN 'COMPLIANCE' THEN DATE_ADD(`createdAt`, INTERVAL 7 YEAR)
  ELSE DATE_ADD(`createdAt`, INTERVAL 2 YEAR)
END;

ALTER TABLE `adminaudit`
  DROP FOREIGN KEY `adminaudit_adminId_fkey`,
  MODIFY COLUMN `adminId` INTEGER NULL,
  ADD COLUMN `retentionClass` VARCHAR(20) NOT NULL DEFAULT 'OPERATIONAL',
  ADD COLUMN `expiresAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldReason` VARCHAR(500) NULL,
  ADD INDEX `adminaudit_expiresAt_legalHoldAt_idx` (`expiresAt`, `legalHoldAt`),
  ADD INDEX `adminaudit_retentionClass_expiresAt_idx` (`retentionClass`, `expiresAt`);

ALTER TABLE `adminaudit`
  ADD CONSTRAINT `adminaudit_adminId_fkey`
  FOREIGN KEY (`adminId`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

UPDATE `adminaudit`
SET
  `retentionClass` = CASE
    WHEN UPPER(`action`) LIKE '%OTP%' THEN 'OTP'
    WHEN UPPER(`action`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX' THEN 'FINANCIAL'
    WHEN UPPER(`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC' THEN 'TECHNICAL'
    WHEN UPPER(`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT' THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END;

UPDATE `adminaudit`
SET `expiresAt` = CASE `retentionClass`
  WHEN 'OTP' THEN DATE_ADD(`createdAt`, INTERVAL 30 DAY)
  WHEN 'TECHNICAL' THEN DATE_ADD(`createdAt`, INTERVAL 90 DAY)
  WHEN 'FINANCIAL' THEN DATE_ADD(`createdAt`, INTERVAL 7 YEAR)
  WHEN 'COMPLIANCE' THEN DATE_ADD(`createdAt`, INTERVAL 7 YEAR)
  ELSE DATE_ADD(`createdAt`, INTERVAL 2 YEAR)
END;

ALTER TABLE `admin_work_item`
  ADD COLUMN `retentionClass` VARCHAR(20) NOT NULL DEFAULT 'OPERATIONAL',
  ADD COLUMN `expiresAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldAt` DATETIME(3) NULL,
  ADD COLUMN `legalHoldReason` VARCHAR(500) NULL,
  ADD INDEX `admin_work_item_expiresAt_legalHoldAt_idx` (`expiresAt`, `legalHoldAt`);

UPDATE `admin_work_item`
SET
  `retentionClass` = CASE WHEN `category` IN ('PAYMENTS', 'CANCELLATIONS') THEN 'FINANCIAL' ELSE 'OPERATIONAL' END,
  `expiresAt` = CASE
    WHEN `status` <> 'RESOLVED' OR `resolvedAt` IS NULL THEN NULL
    WHEN `category` IN ('PAYMENTS', 'CANCELLATIONS') THEN DATE_ADD(`resolvedAt`, INTERVAL 7 YEAR)
    ELSE DATE_ADD(`resolvedAt`, INTERVAL 2 YEAR)
  END;

DROP TRIGGER IF EXISTS `auditlog_retention_before_insert`;
CREATE TRIGGER `auditlog_retention_before_insert`
BEFORE INSERT ON `auditlog`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`expiresAt` IS NOT NULL
      AND NEW.`retentionClass` IN ('OTP', 'TECHNICAL', 'SECURITY', 'OPERATIONAL', 'FINANCIAL', 'COMPLIANCE')
      THEN NEW.`retentionClass`
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' OR UPPER(NEW.`entity`) LIKE 'OTP:%' THEN 'OTP'
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' OR UPPER(NEW.`entity`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      OR UPPER(NEW.`entity`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      THEN 'FINANCIAL'
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      OR UPPER(NEW.`entity`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      THEN 'TECHNICAL'
    WHEN UPPER(NEW.`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      OR UPPER(NEW.`entity`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT'
      THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = COALESCE(NEW.`expiresAt`, CASE
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' OR UPPER(NEW.`entity`) LIKE 'OTP:%' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 30 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      OR UPPER(NEW.`entity`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC'
      THEN DATE_ADD(NEW.`createdAt`, INTERVAL 90 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE|PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      OR UPPER(NEW.`entity`) REGEXP 'KYC|AML|COMPLIANCE|PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX'
      THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    ELSE DATE_ADD(NEW.`createdAt`, INTERVAL 2 YEAR)
  END);

DROP TRIGGER IF EXISTS `adminaudit_retention_before_insert`;
CREATE TRIGGER `adminaudit_retention_before_insert`
BEFORE INSERT ON `adminaudit`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`expiresAt` IS NOT NULL
      AND NEW.`retentionClass` IN ('OTP', 'TECHNICAL', 'SECURITY', 'OPERATIONAL', 'FINANCIAL', 'COMPLIANCE')
      THEN NEW.`retentionClass`
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' THEN 'OTP'
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE' THEN 'COMPLIANCE'
    WHEN UPPER(NEW.`action`) REGEXP 'PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX' THEN 'FINANCIAL'
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC' THEN 'TECHNICAL'
    WHEN UPPER(NEW.`action`) REGEXP 'LOGIN|LOGOUT|AUTH|SESSION|PASSWORD|2FA|SECURITY|ACCESS|IMPERSONAT' THEN 'SECURITY'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = COALESCE(NEW.`expiresAt`, CASE
    WHEN UPPER(NEW.`action`) LIKE '%OTP%' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 30 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'CLIENT_ERROR|API_ERROR|HEALTH|OBSERVABILITY|DIAGNOSTIC' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 90 DAY)
    WHEN UPPER(NEW.`action`) REGEXP 'KYC|AML|COMPLIANCE|PAYMENT|INVOICE|PAYOUT|REFUND|REVENUE|COMMISSION|LEDGER|RECEIPT|DISBURSEMENT|FX' THEN DATE_ADD(NEW.`createdAt`, INTERVAL 7 YEAR)
    ELSE DATE_ADD(NEW.`createdAt`, INTERVAL 2 YEAR)
  END);

DROP TRIGGER IF EXISTS `admin_work_item_retention_before_update`;
CREATE TRIGGER `admin_work_item_retention_before_update`
BEFORE UPDATE ON `admin_work_item`
FOR EACH ROW
SET
  NEW.`retentionClass` = CASE
    WHEN NEW.`category` IN ('PAYMENTS', 'CANCELLATIONS') THEN 'FINANCIAL'
    ELSE 'OPERATIONAL'
  END,
  NEW.`expiresAt` = CASE
    WHEN NEW.`status` <> 'RESOLVED' THEN NULL
    WHEN NEW.`expiresAt` IS NOT NULL THEN NEW.`expiresAt`
    WHEN NEW.`category` IN ('PAYMENTS', 'CANCELLATIONS')
      THEN DATE_ADD(COALESCE(NEW.`resolvedAt`, CURRENT_TIMESTAMP(3)), INTERVAL 7 YEAR)
    ELSE DATE_ADD(COALESCE(NEW.`resolvedAt`, CURRENT_TIMESTAMP(3)), INTERVAL 2 YEAR)
  END;
