"use client";

import { use, useEffect, useState } from "react";
import { CheckCircle2, Loader2, Star } from "lucide-react";
import apiClient from "@/lib/apiClient";

export default function GuestReviewPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [data, setData] = useState<any>(null); const [rating, setRating] = useState(0); const [feedback, setFeedback] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiClient.get(`/api/public/nrms/guest/reviews/${encodeURIComponent(token)}`).then((response) => { setData(response.data.review); if (response.data.review.respondedAt) setDone(true); }).catch((requestError) => setError(requestError?.response?.data?.error || "This review request is unavailable.")); }, [token]);
  const submit = async () => { if (!rating) return; setBusy(true); setError(null); try { await apiClient.post(`/api/public/nrms/guest/reviews/${encodeURIComponent(token)}`, { rating, feedback: feedback.trim() || null }); setDone(true); } catch (requestError: any) { setError(requestError?.response?.data?.error || "Your review could not be submitted."); } finally { setBusy(false); } };
  if (!data && !error) return <main className="flex min-h-screen items-center justify-center bg-neutral-100"><Loader2 className="h-6 w-6 animate-spin text-emerald-700" /></main>;
  return <main className="min-h-screen bg-neutral-100 px-4 py-10"><section className="mx-auto max-w-xl border border-neutral-200 bg-white p-6 shadow-sm"><p className="m-0 text-[10px] font-bold uppercase tracking-[.16em] text-emerald-700">Verified stay feedback</p><h1 className="mb-0 mt-2 text-2xl font-bold text-neutral-950">How was your stay?</h1><p className="mb-0 mt-2 text-sm text-neutral-500">{data ? `${data.guest}, your feedback helps ${data.property} improve the guest experience.` : error}</p>{done ? <div className="mt-8 flex flex-col items-center border border-emerald-200 bg-emerald-50 px-5 py-8 text-center"><CheckCircle2 className="h-9 w-9 text-emerald-700" /><p className="mb-0 mt-3 text-base font-bold text-emerald-950">Thank you for your feedback</p><p className="mb-0 mt-1 text-sm text-emerald-800/75">Your verified-stay response has been recorded.</p></div> : data && <><div className="mt-8 flex justify-center gap-2" aria-label="Rating">{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" onClick={() => setRating(value)} aria-label={`${value} stars`} className="border-0 bg-transparent p-1"><Star className={`h-9 w-9 ${value <= rating ? "fill-amber-400 text-amber-400" : "text-neutral-300"}`} /></button>)}</div><label className="mt-6 grid gap-2 text-xs font-bold text-neutral-700">Tell the hotel what stood out<textarea value={feedback} onChange={(event) => setFeedback(event.target.value)} maxLength={1000} className="min-h-32 rounded-md border border-neutral-300 p-3 text-sm font-normal outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100" placeholder="Cleanliness, service, comfort or anything that could be improved" /></label>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button type="button" disabled={!rating || busy} onClick={() => void submit()} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md border-0 bg-emerald-800 px-4 text-sm font-bold text-white disabled:bg-neutral-200 disabled:text-neutral-500">{busy && <Loader2 className="h-4 w-4 animate-spin" />}Submit verified feedback</button></>}</section></main>;
}
