ALTER TABLE `tour_bookings`
  ADD COLUMN `customerPaymentRef` VARCHAR(120) NULL,
  ADD COLUMN `operatorPayoutRef` VARCHAR(120) NULL,
  ADD COLUMN `operatorCompletedAt` DATETIME(3) NULL,
  ADD COLUMN `customerConfirmedAt` DATETIME(3) NULL,
  ADD COLUMN `disputeWindowEndsAt` DATETIME(3) NULL;

UPDATE `tour_bookings` SET `customerPaymentRef` = `paymentRef` WHERE `paymentRef` IS NOT NULL;
CREATE UNIQUE INDEX `tour_bookings_customerPaymentRef_key` ON `tour_bookings`(`customerPaymentRef`);
CREATE UNIQUE INDEX `tour_bookings_operatorPayoutRef_key` ON `tour_bookings`(`operatorPayoutRef`);

CREATE TABLE `tour_packages` (`id` INTEGER NOT NULL AUTO_INCREMENT, `operatorAgentId` INTEGER NOT NULL, `legacyPackageId` VARCHAR(120) NOT NULL, `version` INTEGER NOT NULL DEFAULT 1, `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT', `name` VARCHAR(200) NOT NULL, `destination` VARCHAR(200) NULL, `category` VARCHAR(100) NULL, `currency` VARCHAR(3) NOT NULL DEFAULT 'TZS', `pricePerPerson` DECIMAL(12,2) NOT NULL DEFAULT 0, `minPax` INTEGER NULL, `maxPax` INTEGER NULL, `content` JSON NOT NULL, `publishedAt` DATETIME(3) NULL, `archivedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `tour_packages_operatorAgentId_legacyPackageId_version_key`(`operatorAgentId`,`legacyPackageId`,`version`), INDEX `tour_packages_status_destination_idx`(`status`,`destination`), PRIMARY KEY (`id`), CONSTRAINT `tour_packages_operatorAgentId_fkey` FOREIGN KEY (`operatorAgentId`) REFERENCES `agent`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `tour_departures` (`id` INTEGER NOT NULL AUTO_INCREMENT, `tourPackageId` INTEGER NOT NULL, `startDate` DATETIME(3) NOT NULL, `endDate` DATETIME(3) NULL, `capacity` INTEGER NOT NULL, `reservedCount` INTEGER NOT NULL DEFAULT 0, `status` VARCHAR(30) NOT NULL DEFAULT 'OPEN', `bookingCutoffAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `tour_departures_tourPackageId_startDate_key`(`tourPackageId`,`startDate`), INDEX `tour_departures_status_startDate_idx`(`status`,`startDate`), PRIMARY KEY (`id`), CONSTRAINT `tour_departures_tourPackageId_fkey` FOREIGN KEY (`tourPackageId`) REFERENCES `tour_packages`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `tour_travelers` (`id` INTEGER NOT NULL AUTO_INCREMENT, `tourBookingId` INTEGER NOT NULL, `legacyMemberId` VARCHAR(120) NULL, `fullName` VARCHAR(180) NOT NULL, `email` VARCHAR(180) NULL, `phone` VARCHAR(50) NULL, `nationality` VARCHAR(100) NULL, `documentType` VARCHAR(40) NULL, `documentNumber` VARCHAR(100) NULL, `documentUrl` VARCHAR(1000) NULL, `permitStatus` VARCHAR(40) NOT NULL DEFAULT 'NOT_REQUIRED', `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', `metadata` JSON NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `tour_travelers_tourBookingId_legacyMemberId_key`(`tourBookingId`,`legacyMemberId`), INDEX `tour_travelers_tourBookingId_status_idx`(`tourBookingId`,`status`), PRIMARY KEY (`id`), CONSTRAINT `tour_travelers_tourBookingId_fkey` FOREIGN KEY (`tourBookingId`) REFERENCES `tour_bookings`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `tour_cases` (`id` INTEGER NOT NULL AUTO_INCREMENT, `tourBookingId` INTEGER NOT NULL, `type` VARCHAR(40) NOT NULL, `status` VARCHAR(40) NOT NULL DEFAULT 'OPEN', `severity` VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', `title` VARCHAR(180) NOT NULL, `description` TEXT NOT NULL, `requestedByUserId` INTEGER NULL, `assignedToUserId` INTEGER NULL, `requestedStartDate` DATETIME(3) NULL, `requestedEndDate` DATETIME(3) NULL, `resolution` TEXT NULL, `resolutionAmount` DECIMAL(12,2) NULL, `withdrawnAt` DATETIME(3) NULL, `closedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, INDEX `tour_cases_tourBookingId_status_idx`(`tourBookingId`,`status`), INDEX `tour_cases_type_status_severity_idx`(`type`,`status`,`severity`), PRIMARY KEY (`id`), CONSTRAINT `tour_cases_tourBookingId_fkey` FOREIGN KEY (`tourBookingId`) REFERENCES `tour_bookings`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `tour_case_events` (`id` INTEGER NOT NULL AUTO_INCREMENT, `tourCaseId` INTEGER NOT NULL, `actorUserId` INTEGER NULL, `type` VARCHAR(50) NOT NULL, `message` TEXT NULL, `data` JSON NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `tour_case_events_tourCaseId_createdAt_idx`(`tourCaseId`,`createdAt`), PRIMARY KEY (`id`), CONSTRAINT `tour_case_events_tourCaseId_fkey` FOREIGN KEY (`tourCaseId`) REFERENCES `tour_cases`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `tour_financial_transactions` (`id` INTEGER NOT NULL AUTO_INCREMENT, `tourBookingId` INTEGER NOT NULL, `kind` VARCHAR(30) NOT NULL, `status` VARCHAR(30) NOT NULL, `provider` VARCHAR(50) NULL, `reference` VARCHAR(160) NULL, `idempotencyKey` VARCHAR(160) NULL, `currency` VARCHAR(3) NOT NULL, `amount` DECIMAL(12,2) NOT NULL, `metadata` JSON NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `tour_financial_transactions_reference_key`(`reference`), UNIQUE INDEX `tour_financial_transactions_idempotencyKey_key`(`idempotencyKey`), INDEX `tour_financial_transactions_tourBookingId_kind_status_idx`(`tourBookingId`,`kind`,`status`), PRIMARY KEY (`id`), CONSTRAINT `tour_financial_transactions_tourBookingId_fkey` FOREIGN KEY (`tourBookingId`) REFERENCES `tour_bookings`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
