/* eslint-disable react/forbid-dom-props */
/* CSS inline styles are required for responsive box-sizing and width constraints */
"use client";
import { useEffect, useState, useMemo } from "react";
import { Bell, Truck, Search, AlertCircle, Info, AlertTriangle, Plus, X, Shield, FileWarning, Calendar, Car, Bike, CarTaxiFront, Target, RefreshCw, XCircle } from "lucide-react";
import apiClient from "@/lib/apiClient";
import { useAdminQueryId } from "@/lib/adminRecordRefs";
import { useSearchParams } from "next/navigation";

const api = apiClient;
function authify() {}

type Driver = {
  id: number;
  name: string;
  email: string;
  vehicleType?: string;
};

type ReminderData = {
  driver: Driver;
  total: number;
  page: number;
  pageSize: number;
  items: Array<{
    id: string;
    type: "INFO" | "WARNING" | "ALERT" | "PROMOTION" | "POLICY_VIOLATION" | "SAFETY" | "LICENSE_EXPIRY" | "INSURANCE_EXPIRY";
    message: string;
    action: string | null;
    actionLink: string | null;
    expiresAt: string | null;
    isRead?: boolean;
    read?: boolean;
    createdAt: string;
  }>;
};

type ReminderType = "POLICY_VIOLATION" | "SAFETY" | "LICENSE_EXPIRY" | "INSURANCE_EXPIRY" | "WARNING" | "INFO" | "ALERT";

type NoticeState = {
  kind: "success" | "error" | "info";
  title: string;
  message: string;
} | null;

const REMINDER_TYPES: Array<{ value: ReminderType; label: string; icon: any; description: string; color: string }> = [
  { value: "POLICY_VIOLATION", label: "Policy Violation", icon: FileWarning, description: "Driver violated company policy", color: "bg-red-100 text-red-700 border-red-200" },
  { value: "SAFETY", label: "Safety Measure", icon: Shield, description: "Safety reminder (e.g., helmet for Motorcycle)", color: "bg-amber-100 text-amber-700 border-amber-200" },
  { value: "LICENSE_EXPIRY", label: "License Expiration", icon: Calendar, description: "Driver license is expiring soon", color: "bg-orange-100 text-orange-700 border-orange-200" },
  { value: "INSURANCE_EXPIRY", label: "Insurance Expiration", icon: Calendar, description: "Insurance is expiring soon", color: "bg-purple-100 text-purple-700 border-purple-200" },
  { value: "WARNING", label: "Warning", icon: AlertTriangle, description: "General warning reminder", color: "bg-yellow-100 text-yellow-700 border-yellow-200" },
  { value: "INFO", label: "Information", icon: Info, description: "General information reminder", color: "bg-blue-100 text-blue-700 border-blue-200" },
  { value: "ALERT", label: "Alert", icon: AlertCircle, description: "Urgent alert reminder", color: "bg-red-100 text-red-700 border-red-200" },
];

const getReminderIcon = (type: string) => {
  const reminderType = REMINDER_TYPES.find(r => r.value === type);
  return reminderType?.icon || Info;
};

export default function AdminDriversRemindersPage() {
  const searchParams = useSearchParams();
  const queryDriverId = useAdminQueryId("driver", searchParams?.get("driverId"), "driverId");
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [selectedDriver, setSelectedDriver] = useState<number | null>(null);
  const [reminderData, setReminderData] = useState<ReminderData | null>(null);
  const [search, setSearch] = useState("");
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [creating, setCreating] = useState(false);
  const [typeFilter, setTypeFilter] = useState<ReminderType | "ALL">("ALL");
  const [statusFilter, setStatusFilter] = useState<"ALL" | "UNREAD" | "READ" | "EXPIRED" | "ACTIVE">("ALL");
  const [expiringDocuments, setExpiringDocuments] = useState<Array<{ driver: Driver; expiringDocuments: Array<{ type: string; expiryDate: string; daysLeft: number }> }>>([]);
  const [autoCreating, setAutoCreating] = useState(false);
  
  // Advanced filters
  const [selectedTypes, setSelectedTypes] = useState<Set<ReminderType>>(new Set());
  const [selectedStatuses, setSelectedStatuses] = useState<Set<"UNREAD" | "READ" | "EXPIRED" | "ACTIVE">>(new Set());
  const [dateRange, setDateRange] = useState<{ start: string; end: string }>({ start: "", end: "" });
  const [autoGeneratedFilter, setAutoGeneratedFilter] = useState<"ALL" | "AUTO" | "MANUAL">("ALL");
  const [priorityFilter, setPriorityFilter] = useState<"ALL" | "HIGH" | "MEDIUM" | "LOW">("ALL");
  const [activeFilters, setActiveFilters] = useState<Array<{ key: string; label: string; value: string }>>([]);
  const [reminderSearch, setReminderSearch] = useState("");
  const [sortBy, setSortBy] = useState<"NEWEST" | "OLDEST" | "PRIORITY" | "EXPIRY">("NEWEST");
  
  // Create reminder form state
  const [reminderType, setReminderType] = useState<ReminderType>("INFO");
  const [reminderMessage, setReminderMessage] = useState("");
  const [reminderAction, setReminderAction] = useState("");
  const [reminderActionLink, setReminderActionLink] = useState("");
  const [reminderExpiresAt, setReminderExpiresAt] = useState("");
  const [reminderGoal, setReminderGoal] = useState("");
  const [notice, setNotice] = useState<NoticeState>(null);

  function showNotice(kind: "success" | "error" | "info", title: string, message: string) {
    setNotice({ kind, title, message });
  }

  useEffect(() => {
    authify();
    loadDrivers();
    loadExpiringDocuments();
  }, []);

  useEffect(() => {
    const id = queryDriverId ?? 0;
    if (!Number.isFinite(id) || id <= 0) return;
    if (!drivers.length) return;
    if (selectedDriver === id) return;
    const exists = drivers.some((d) => d.id === id);
    if (!exists) return;
    loadDriverReminders(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queryDriverId, drivers]);

  async function loadExpiringDocuments() {
    try {
      const r = await api.get<{ drivers: Array<{ driver: Driver; expiringDocuments: Array<{ type: string; expiryDate: string; daysLeft: number }> }> }>("/api/admin/drivers/expiring-documents");
      setExpiringDocuments(r.data?.drivers ?? []);
    } catch (err: any) {
      // Only log non-4xx errors to avoid console spam for expected errors (e.g., missing tables, permissions)
      if (!err?.response || err.response.status >= 500) {
        console.error("Failed to load expiring documents", err);
      } else {
        console.debug("Could not load expiring documents (expected):", err.response?.status, err.response?.data);
      }
      setExpiringDocuments([]);
    }
  }

  async function autoCreateReminders() {
    setAutoCreating(true);
    try {
      const r = await api.post<{ created: number; reminders: any[]; stats: { license: number; insurance: number; rating: number; safety: number; security: number; goals: number; earnings: number } }>("/api/admin/drivers/auto-create-reminders");
      const stats = r.data.stats || {};
      const message = `Successfully created ${r.data.created} automatic reminders:\n` +
        `• License Expiry: ${stats.license}\n` +
        `• Insurance Expiry: ${stats.insurance}\n` +
        `• Rating-based: ${stats.rating}\n` +
        `• Safety: ${stats.safety}\n` +
        `• Security: ${stats.security}\n` +
        `• Goals: ${stats.goals}\n` +
        `• Earnings: ${stats.earnings}`;
      showNotice("success", "Automatic reminders created", message);
      await loadExpiringDocuments();
      if (selectedDriver) {
        await loadDriverReminders(selectedDriver);
      }
    } catch (err) {
      console.error("Failed to auto-create reminders", err);
      showNotice("error", "Automatic reminder creation failed", "Failed to auto-create reminders. Please try again.");
    } finally {
      setAutoCreating(false);
    }
  }

  async function loadDrivers() {
    try {
      const r = await api.get<{ items: Driver[]; total: number }>("/api/admin/drivers", { params: { page: 1, pageSize: 100 } });
      setDrivers(r.data?.items ?? []);
    } catch (err) {
      console.error("Failed to load drivers", err);
      setDrivers([]);
    }
  }

  async function loadDriverReminders(driverId: number) {
    try {
      const r = await api.get<ReminderData>(`/api/admin/drivers/${driverId}/reminders`, { params: { page: 1, pageSize: 50 } });
      if (r.data) {
        const normalized = {
          ...r.data,
          items: (r.data.items || []).map((it: any) => ({
            ...it,
            isRead: Boolean(it?.isRead ?? it?.read),
          })),
        };
        setReminderData(normalized);
      } else {
        const driver = drivers.find(d => d.id === driverId);
        if (driver) {
          setReminderData({
            driver,
            total: 0,
            page: 1,
            pageSize: 50,
            items: [],
          });
        }
      }
      setSelectedDriver(driverId);
    } catch (err) {
      console.error("Failed to load driver reminders", err);
      const driver = drivers.find(d => d.id === driverId);
      if (driver) {
        setReminderData({
          driver,
          total: 0,
          page: 1,
          pageSize: 50,
          items: [],
        });
      }
      setSelectedDriver(driverId);
    }
  }

  async function createReminder() {
    if (!selectedDriver || !reminderMessage.trim()) return;

    setCreating(true);
    try {
      const payload: any = {
        driverId: selectedDriver,
        type: reminderType,
        message: reminderMessage.trim(),
        action: reminderAction.trim() || null,
        actionLink: reminderActionLink.trim() || null,
        expiresAt: reminderExpiresAt || null,
      };

      // Add goal to meta if provided
      if (reminderGoal.trim()) {
        payload.meta = { goal: reminderGoal.trim() };
      }

      await api.post(`/api/admin/drivers/${selectedDriver}/reminders`, payload);
      
      // Reset form
      setReminderMessage("");
      setReminderAction("");
      setReminderActionLink("");
      setReminderExpiresAt("");
      setReminderGoal("");
      setReminderType("INFO");
      setShowCreateModal(false);
      showNotice("success", "Reminder created", "The reminder was created and sent through the admin reminder channel.");
      
      // Reload reminders
      if (selectedDriver) {
        await loadDriverReminders(selectedDriver);
      }
    } catch (err: any) {
      // Handle 501 (Not Implemented) - reminders feature not enabled
      if (err?.response?.status === 501) {
        console.debug("Reminders feature not enabled:", err.response?.data);
        showNotice("error", "Reminders unavailable", "Reminders feature is not enabled. The driver reminders table may not be set up in the database.");
      } else if (err?.response?.status === 403) {
        console.debug("Permission denied:", err.response?.data);
        showNotice("error", "Permission denied", "Only authenticated admins can create reminders from this page.");
      } else if (err?.response?.status === 400) {
        const errorMsg = err.response?.data?.error || "Invalid request data";
        showNotice("error", "Reminder creation failed", `Failed to create reminder: ${errorMsg}`);
      } else {
        console.error("Failed to create reminder", err);
        showNotice("error", "Reminder creation failed", "Failed to create reminder. Please try again.");
      }
    } finally {
      setCreating(false);
    }
  }

  // Auto-fill message based on reminder type
  useEffect(() => {
    if (reminderType === "SAFETY" && selectedDriver) {
      const driver = drivers.find(d => d.id === selectedDriver);
      if (driver?.vehicleType === "MotorCycle") {
        setReminderMessage("Please ensure you always wear a helmet while driving. Safety is our top priority.");
      } else {
        setReminderMessage("Please follow all safety measures while driving. Safety is our top priority.");
      }
    } else if (reminderType === "LICENSE_EXPIRY") {
      setReminderMessage("Your driver's license is expiring soon. Please renew it before the expiration date to avoid service interruption.");
    } else if (reminderType === "INSURANCE_EXPIRY") {
      setReminderMessage("Your vehicle insurance is expiring soon. Please renew it before the expiration date to maintain coverage.");
    } else if (reminderType === "POLICY_VIOLATION") {
      setReminderMessage("");
    }
  }, [reminderType, selectedDriver, drivers]);

  const filteredDrivers = drivers.filter(
    (d) => d.name.toLowerCase().includes(search.toLowerCase()) || d.email.toLowerCase().includes(search.toLowerCase())
  );

  // Advanced filtering logic
  const filteredReminders = useMemo(() => {
    if (!reminderData) return [];
    
    let filtered = reminderData.items;

    // Advanced type filtering (multi-select)
    if (selectedTypes.size > 0) {
      filtered = filtered.filter(r => selectedTypes.has(r.type as ReminderType));
    } else if (typeFilter !== "ALL") {
      filtered = filtered.filter(r => r.type === typeFilter);
    }

    // Advanced status filtering (multi-select)
    if (selectedStatuses.size > 0) {
      filtered = filtered.filter(r => {
        if (selectedStatuses.has("UNREAD") && !r.isRead) return true;
        if (selectedStatuses.has("READ") && r.isRead) return true;
        if (selectedStatuses.has("EXPIRED") && r.expiresAt && new Date(r.expiresAt) < new Date()) return true;
        if (selectedStatuses.has("ACTIVE") && (!r.expiresAt || new Date(r.expiresAt) > new Date())) return true;
        return false;
      });
    } else if (statusFilter !== "ALL") {
      if (statusFilter === "UNREAD") {
        filtered = filtered.filter(r => !r.isRead);
      } else if (statusFilter === "READ") {
        filtered = filtered.filter(r => r.isRead);
      } else if (statusFilter === "EXPIRED") {
        filtered = filtered.filter(r => r.expiresAt && new Date(r.expiresAt) < new Date());
      } else if (statusFilter === "ACTIVE") {
        filtered = filtered.filter(r => !r.expiresAt || new Date(r.expiresAt) > new Date());
      }
    }

    // Date range filter
    if (dateRange.start) {
      const startDate = new Date(dateRange.start);
      startDate.setHours(0, 0, 0, 0);
      filtered = filtered.filter(r => new Date(r.createdAt) >= startDate);
    }
    if (dateRange.end) {
      const endDate = new Date(dateRange.end);
      endDate.setHours(23, 59, 59, 999);
      filtered = filtered.filter(r => new Date(r.createdAt) <= endDate);
    }

    // Auto-generated filter
    if (autoGeneratedFilter !== "ALL") {
      filtered = filtered.filter(r => {
        const meta = (r as any).meta || {};
        const isAuto = meta.autoGenerated === true;
        return autoGeneratedFilter === "AUTO" ? isAuto : !isAuto;
      });
    }

    // Priority filter (based on type)
    if (priorityFilter !== "ALL") {
      filtered = filtered.filter(r => {
        if (priorityFilter === "HIGH") {
          return r.type === "ALERT" || r.type === "POLICY_VIOLATION";
        } else if (priorityFilter === "MEDIUM") {
          return r.type === "WARNING" || r.type === "LICENSE_EXPIRY" || r.type === "INSURANCE_EXPIRY";
        } else if (priorityFilter === "LOW") {
          return r.type === "INFO" || r.type === "SAFETY";
        }
        return true;
      });
    }

    // Search filter
    if (reminderSearch.trim()) {
      const searchLower = reminderSearch.toLowerCase();
      filtered = filtered.filter(r => 
        r.message.toLowerCase().includes(searchLower) ||
        r.type.toLowerCase().includes(searchLower) ||
        (r.action && r.action.toLowerCase().includes(searchLower))
      );
    }

    // Sorting
    filtered.sort((a, b) => {
      if (sortBy === "NEWEST") {
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      } else if (sortBy === "OLDEST") {
        return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
      } else if (sortBy === "PRIORITY") {
        const priorityOrder: Record<string, number> = {
          "ALERT": 1,
          "POLICY_VIOLATION": 2,
          "WARNING": 3,
          "LICENSE_EXPIRY": 4,
          "INSURANCE_EXPIRY": 5,
          "SAFETY": 6,
          "INFO": 7,
        };
        return (priorityOrder[a.type] || 99) - (priorityOrder[b.type] || 99);
      } else if (sortBy === "EXPIRY") {
        if (!a.expiresAt && !b.expiresAt) return 0;
        if (!a.expiresAt) return 1;
        if (!b.expiresAt) return -1;
        return new Date(a.expiresAt).getTime() - new Date(b.expiresAt).getTime();
      }
      return 0;
    });

    return filtered;
  }, [reminderData, typeFilter, statusFilter, selectedTypes, selectedStatuses, dateRange, autoGeneratedFilter, priorityFilter, reminderSearch, sortBy]);

  // Update active filters display
  useEffect(() => {
    const active: Array<{ key: string; label: string; value: string }> = [];
    
    if (selectedTypes.size > 0) {
      selectedTypes.forEach(type => {
        const typeLabel = REMINDER_TYPES.find(t => t.value === type)?.label || type;
        active.push({ key: `type-${type}`, label: "Type", value: typeLabel });
      });
    }
    
    if (selectedStatuses.size > 0) {
      selectedStatuses.forEach(status => {
        active.push({ key: `status-${status}`, label: "Status", value: status });
      });
    }
    
    if (dateRange.start) {
      active.push({ key: "date-start", label: "From", value: new Date(dateRange.start).toLocaleDateString() });
    }
    
    if (dateRange.end) {
      active.push({ key: "date-end", label: "To", value: new Date(dateRange.end).toLocaleDateString() });
    }
    
    if (autoGeneratedFilter !== "ALL") {
      active.push({ key: "auto", label: "Source", value: autoGeneratedFilter === "AUTO" ? "Auto-generated" : "Manual" });
    }
    
    if (priorityFilter !== "ALL") {
      active.push({ key: "priority", label: "Priority", value: priorityFilter });
    }
    
    setActiveFilters(active);
  }, [selectedTypes, selectedStatuses, dateRange, autoGeneratedFilter, priorityFilter]);

  // Filter presets
  const filterPresets = [
    {
      name: "Urgent Reminders",
      apply: () => {
        setSelectedTypes(new Set(["ALERT", "POLICY_VIOLATION"]));
        setSelectedStatuses(new Set(["UNREAD"]));
        setPriorityFilter("HIGH");
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Expiring Documents",
      apply: () => {
        setSelectedTypes(new Set(["LICENSE_EXPIRY", "INSURANCE_EXPIRY"]));
        setSelectedStatuses(new Set(["ACTIVE", "UNREAD"]));
        setPriorityFilter("MEDIUM");
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Auto-Generated",
      apply: () => {
        setAutoGeneratedFilter("AUTO");
        setSelectedTypes(new Set());
        setSelectedStatuses(new Set());
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "Unread Only",
      apply: () => {
        setSelectedStatuses(new Set(["UNREAD"]));
        setSelectedTypes(new Set());
        setTypeFilter("ALL");
        setStatusFilter("ALL");
      },
    },
    {
      name: "This Week",
      apply: () => {
        const today = new Date();
        const weekAgo = new Date(today);
        weekAgo.setDate(weekAgo.getDate() - 7);
        setDateRange({
          start: weekAgo.toISOString().split('T')[0],
          end: today.toISOString().split('T')[0],
        });
      },
    },
  ];

  // Clear all filters
  const clearAllFilters = () => {
    setSelectedTypes(new Set());
    setSelectedStatuses(new Set());
    setDateRange({ start: "", end: "" });
    setAutoGeneratedFilter("ALL");
    setPriorityFilter("ALL");
    setTypeFilter("ALL");
    setStatusFilter("ALL");
    setReminderSearch("");
  };


  // Calculate statistics
  const reminderStats = useMemo(() => {
    if (!reminderData) return { total: 0, unread: 0, expired: 0, byType: {} };
    
    return {
      total: reminderData.items.length,
      unread: reminderData.items.filter(r => !r.isRead).length,
      expired: reminderData.items.filter(r => r.expiresAt && new Date(r.expiresAt) < new Date()).length,
      byType: reminderData.items.reduce((acc: any, r) => {
        acc[r.type] = (acc[r.type] || 0) + 1;
        return acc;
      }, {}),
    };
  }, [reminderData]);

  return (
    <div className="space-y-6">
      {/* Premium Banner */}
      <div style={{ position: "relative", borderRadius: "1.25rem", overflow: "hidden", background: "linear-gradient(135deg, #0e2a7a 0%, #0a5c82 38%, #02665e 100%)", boxShadow: "0 28px 65px -15px rgba(2,102,94,0.45), 0 8px 22px -8px rgba(14,42,122,0.50)", padding: "2rem 2rem 1.75rem" }}>
        <svg style={{ position: "absolute", inset: 0, width: "100%", height: "100%", opacity: 0.13, pointerEvents: "none" }} viewBox="0 0 900 160" preserveAspectRatio="xMidYMid slice">
          <circle cx="820" cy="30" r="90" fill="none" stroke="white" strokeWidth="1.2" />
          <circle cx="820" cy="30" r="55" fill="none" stroke="white" strokeWidth="0.7" />
          <circle cx="60" cy="140" r="70" fill="none" stroke="white" strokeWidth="1.0" />
          <line x1="0" y1="40" x2="900" y2="40" stroke="white" strokeWidth="0.4" />
          <line x1="0" y1="72" x2="900" y2="72" stroke="white" strokeWidth="0.4" />
          <line x1="0" y1="104" x2="900" y2="104" stroke="white" strokeWidth="0.4" />
          <line x1="0" y1="136" x2="900" y2="136" stroke="white" strokeWidth="0.4" />
          <polyline points="0,130 90,110 180,95 270,80 360,65 450,90 540,55 630,70 720,40 810,52 900,35" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
          <polygon points="0,130 90,110 180,95 270,80 360,65 450,90 540,55 630,70 720,40 810,52 900,35 900,160 0,160" fill="white" opacity={0.06} />
          <polyline points="0,145 90,132 180,118 270,128 360,108 450,122 540,98 630,112 720,88 810,102 900,78" fill="none" stroke="white" strokeWidth="1.2" strokeDasharray="6 4" opacity={0.5} />
          <circle cx="540" cy="55" r="5" fill="white" opacity={0.75} />
          <circle cx="720" cy="40" r="5" fill="white" opacity={0.75} />
          <circle cx="900" cy="35" r="5" fill="white" opacity={0.75} />
          <defs><radialGradient id="remBannerGlow" cx="50%" cy="50%" r="50%"><stop offset="0%" stopColor="white" stopOpacity="0.12" /><stop offset="100%" stopColor="white" stopOpacity="0" /></radialGradient></defs>
          <ellipse cx="450" cy="90" rx="200" ry="70" fill="url(#remBannerGlow)" />
        </svg>
        <div style={{ position: "relative", zIndex: 1, display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: "1rem", marginBottom: "1.5rem" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
            <div style={{ width: 46, height: 46, borderRadius: "50%", background: "rgba(255,255,255,0.10)", border: "1.5px solid rgba(255,255,255,0.18)", boxShadow: "0 0 0 8px rgba(255,255,255,0.05)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
              <Bell style={{ width: 22, height: 22, color: "white" }} />
            </div>
            <div>
              <h1 style={{ fontSize: "1.35rem", fontWeight: 800, color: "white", margin: 0, letterSpacing: "-0.01em" }}>Driver Reminders</h1>
              <p style={{ fontSize: "0.78rem", color: "rgba(255,255,255,0.62)", margin: "2px 0 0" }}>Policy alerts · license &amp; insurance expiry · safety notifications</p>
            </div>
          </div>
          {expiringDocuments.length > 0 && (
            <button
              onClick={autoCreateReminders}
              disabled={autoCreating}
              style={{ display: "flex", alignItems: "center", gap: "0.4rem", padding: "0.5rem 1.1rem", background: autoCreating ? "rgba(245,158,11,0.25)" : "rgba(245,158,11,0.22)", border: "1px solid rgba(245,158,11,0.55)", borderRadius: "0.75rem", color: "#fcd34d", fontSize: "0.82rem", fontWeight: 600, cursor: autoCreating ? "not-allowed" : "pointer", flexShrink: 0 }}
            >
              <RefreshCw style={{ width: 14, height: 14 }} className={autoCreating ? "animate-spin" : ""} />
              {autoCreating ? "Creating..." : "Auto-Create Reminders"}
            </button>
          )}
        </div>
        <div style={{ position: "relative", zIndex: 1, display: "flex", flexWrap: "wrap", gap: "0.75rem" }}>
          <div style={{ background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.20)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 90 }}>
            <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(255,255,255,0.70)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Drivers</div>
            <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "white", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>{drivers.length}</div>
          </div>
          <div style={{ background: "rgba(245,158,11,0.16)", border: "1px solid rgba(245,158,11,0.35)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 120 }}>
            <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(252,211,77,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Expiring Docs</div>
            <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "#fcd34d", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>
              {expiringDocuments.reduce((s, d) => s + d.expiringDocuments.length, 0)}
            </div>
            {expiringDocuments.length > 0 && (
              <div style={{ fontSize: "0.63rem", color: "rgba(255,255,255,0.45)", marginTop: 2 }}>{expiringDocuments.length} driver{expiringDocuments.length > 1 ? 's' : ''}</div>
            )}
          </div>
          {reminderData && (
            <>
              <div style={{ background: "rgba(99,102,241,0.16)", border: "1px solid rgba(99,102,241,0.35)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 90 }}>
                <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(196,181,253,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Total</div>
                <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "#c4b5fd", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>{reminderStats.total}</div>
              </div>
              <div style={{ background: "rgba(245,158,11,0.16)", border: "1px solid rgba(245,158,11,0.35)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 90 }}>
                <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(252,211,77,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Unread</div>
                <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "#fcd34d", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>{reminderStats.unread}</div>
              </div>
              <div style={{ background: "rgba(239,68,68,0.14)", border: "1px solid rgba(239,68,68,0.32)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 90 }}>
                <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(252,165,165,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Expired</div>
                <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "#fca5a5", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>{reminderStats.expired}</div>
              </div>
              <div style={{ background: "rgba(16,185,129,0.16)", border: "1px solid rgba(16,185,129,0.35)", borderRadius: "0.85rem", padding: "0.6rem 1rem", minWidth: 90 }}>
                <div style={{ fontSize: "0.63rem", fontWeight: 700, color: "rgba(110,231,183,0.85)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Active</div>
                <div style={{ fontSize: "1.3rem", fontWeight: 900, color: "#6ee7b7", fontVariantNumeric: "tabular-nums", lineHeight: 1.2 }}>
                  {reminderData.items.filter(r => !r.expiresAt || new Date(r.expiresAt) > new Date()).length}
                </div>
              </div>
            </>
          )}
        </div>
      </div>

      {notice && (
        <div
          className="rounded-2xl border px-4 py-4 shadow-sm"
          style={{
            background:
              notice.kind === "success"
                ? "linear-gradient(135deg, rgba(6,95,70,0.18), rgba(16,185,129,0.12))"
                : notice.kind === "error"
                  ? "linear-gradient(135deg, rgba(127,29,29,0.18), rgba(239,68,68,0.12))"
                  : "linear-gradient(135deg, rgba(30,64,175,0.18), rgba(59,130,246,0.12))",
            borderColor:
              notice.kind === "success"
                ? "rgba(16,185,129,0.28)"
                : notice.kind === "error"
                  ? "rgba(239,68,68,0.28)"
                  : "rgba(59,130,246,0.28)",
          }}
        >
          <div className="flex items-start justify-between gap-4">
            <div>
              <div
                className="text-sm font-semibold"
                style={{
                  color:
                    notice.kind === "success"
                      ? "#86efac"
                      : notice.kind === "error"
                        ? "#fca5a5"
                        : "#93c5fd",
                }}
              >
                {notice.title}
              </div>
              <div className="mt-1 whitespace-pre-line text-sm" style={{ color: "rgba(255,255,255,0.82)" }}>
                {notice.message}
              </div>
            </div>
            <button
              type="button"
              onClick={() => setNotice(null)}
              className="rounded-full p-1 transition-colors"
              style={{ background: "rgba(255,255,255,0.08)", color: "rgba(255,255,255,0.72)" }}
              aria-label="Dismiss notice"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 w-full">
        <div className="lg:col-span-1 w-full min-w-0 max-w-full">
          <div style={{ borderRadius: "1rem", border: "1px solid rgba(255,255,255,0.08)", boxShadow: "0 8px 32px rgba(0,0,0,0.45), inset 0 1px 0 rgba(255,255,255,0.06)", background: "linear-gradient(135deg, #0a1a19 0%, #0d2320 60%, #0a1f2e 100%)", overflow: "hidden" }} className="w-full">
            <div style={{ padding: "0.75rem", borderBottom: "1px solid rgba(255,255,255,0.07)", boxSizing: "border-box", maxWidth: "100%", overflow: "hidden" }} className="w-full">
              <div className="relative w-full" style={{ maxWidth: "100%", boxSizing: "border-box" }}>
                <Search className="absolute left-2.5 top-1/2 transform -translate-y-1/2 h-4 w-4 pointer-events-none z-10" style={{ color: "rgba(255,255,255,0.35)" }} />
                <input
                  type="text"
                  placeholder="Search drivers..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 rounded-lg text-sm outline-none"
                  style={{ 
                    boxSizing: "border-box", 
                    maxWidth: "100%",
                    width: "100%",
                    background: "rgba(255,255,255,0.07)",
                    border: "1px solid rgba(255,255,255,0.12)",
                    color: "rgba(255,255,255,0.88)",
                  }}
                />
              </div>
            </div>
            <div className="max-h-[600px] overflow-y-auto" style={{ scrollbarColor: "rgba(255,255,255,0.15) transparent" }}>
              {filteredDrivers.map((driver) => (
                <div
                  key={driver.id}
                  onClick={() => loadDriverReminders(driver.id)}
                  className="p-4 cursor-pointer transition-colors"
                  style={{ borderBottom: "1px solid rgba(255,255,255,0.05)", borderLeft: selectedDriver === driver.id ? "4px solid #059669" : "4px solid transparent", background: selectedDriver === driver.id ? "rgba(16,185,129,0.15)" : undefined }}
                >
                  <div className="flex items-center gap-3">
                    <div style={{ width: 40, height: 40, borderRadius: "50%", background: selectedDriver === driver.id ? "linear-gradient(135deg,#059669,#047857)" : "rgba(16,185,129,0.18)", border: "1px solid rgba(16,185,129,0.25)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                      {driver.vehicleType === "Car" ? (
                        <Car className="h-5 w-5" style={{ color: selectedDriver === driver.id ? "white" : "#6ee7b7" }} />
                      ) : driver.vehicleType === "MotorCycle" ? (
                        <Bike className="h-5 w-5" style={{ color: selectedDriver === driver.id ? "white" : "#6ee7b7" }} />
                      ) : driver.vehicleType === "Tuktuk" ? (
                        <CarTaxiFront className="h-5 w-5" style={{ color: selectedDriver === driver.id ? "white" : "#6ee7b7" }} />
                      ) : (
                        <Truck className="h-5 w-5" style={{ color: selectedDriver === driver.id ? "white" : "#6ee7b7" }} />
                      )}
                    </div>
                    <div>
                      <p className="font-medium" style={{ color: "rgba(255,255,255,0.90)" }}>{driver.name}</p>
                      <p className="text-xs" style={{ color: "rgba(255,255,255,0.45)" }}>{driver.email}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
          {reminderData ? (
            <div className="space-y-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
              <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-4 md:p-6 overflow-hidden" style={{ background: "linear-gradient(135deg, #0a1a19 0%, #0d2320 60%, #0a1f2e 100%)", border: "1px solid rgba(255,255,255,0.08)", boxSizing: 'border-box', maxWidth: '100%', width: '100%' }}>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                  <div className="min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <h2 className="text-xl font-bold mb-2 truncate" style={{ color: "rgba(255,255,255,0.92)" }}>{reminderData.driver.name}</h2>
                    <p className="text-sm truncate" style={{ color: "rgba(255,255,255,0.50)" }}>{reminderData.driver.email}</p>
                  </div>
                  <button
                    onClick={() => setShowCreateModal(true)}
                    className="px-3 md:px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-all flex items-center gap-2 whitespace-nowrap flex-shrink-0"
                    style={{ boxSizing: 'border-box' }}
                  >
                    <Plus className="h-4 w-4" />
                    <span className="hidden sm:inline">Create Reminder</span>
                    <span className="sm:hidden">Create</span>
                  </button>
                </div>
                
                {/* Statistics Cards */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4 mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                  <div className="p-3 md:p-4 rounded-lg min-w-0" style={{ background: "rgba(99,102,241,0.16)", border: "1px solid rgba(99,102,241,0.30)", boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium mb-1 truncate" style={{ color: "rgba(196,181,253,0.80)" }}>Total</p>
                    <p className="text-xl md:text-2xl font-bold truncate" style={{ color: "#c4b5fd" }}>{reminderStats.total}</p>
                  </div>
                  <div className="p-3 md:p-4 rounded-lg min-w-0" style={{ background: "rgba(245,158,11,0.16)", border: "1px solid rgba(245,158,11,0.30)", boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium mb-1 truncate" style={{ color: "rgba(252,211,77,0.80)" }}>Unread</p>
                    <p className="text-xl md:text-2xl font-bold truncate" style={{ color: "#fcd34d" }}>{reminderStats.unread}</p>
                  </div>
                  <div className="p-3 md:p-4 rounded-lg min-w-0" style={{ background: "rgba(239,68,68,0.14)", border: "1px solid rgba(239,68,68,0.28)", boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium mb-1 truncate" style={{ color: "rgba(252,165,165,0.80)" }}>Expired</p>
                    <p className="text-xl md:text-2xl font-bold truncate" style={{ color: "#fca5a5" }}>{reminderStats.expired}</p>
                  </div>
                  <div className="p-3 md:p-4 rounded-lg min-w-0" style={{ background: "rgba(16,185,129,0.16)", border: "1px solid rgba(16,185,129,0.30)", boxSizing: 'border-box', maxWidth: '100%' }}>
                    <p className="text-xs md:text-sm font-medium mb-1 truncate" style={{ color: "rgba(110,231,183,0.80)" }}>Active</p>
                    <p className="text-xl md:text-2xl font-bold truncate" style={{ color: "#6ee7b7" }}>
                      {reminderData.items.filter((r) => !r.expiresAt || new Date(r.expiresAt) > new Date()).length}
                    </p>
                  </div>
                </div>

                {/* Quick Filters Only */}
                <div className="mb-6 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                  <div className="flex flex-wrap items-center gap-2" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <span className="text-sm font-medium whitespace-nowrap" style={{ color: "rgba(255,255,255,0.55)" }}>Quick Filters:</span>
                    {filterPresets.map((preset, idx) => (
                      <button
                        key={idx}
                        onClick={preset.apply}
                        className="px-4 py-1.5 text-sm font-medium rounded-full transition-all whitespace-nowrap"
                        style={{ background: "rgba(16,185,129,0.14)", border: "1px solid rgba(16,185,129,0.30)", color: "#6ee7b7", boxSizing: 'border-box' }}
                      >
                        {preset.name}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-4 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                    <h3 className="text-lg font-semibold whitespace-nowrap" style={{ color: "rgba(255,255,255,0.88)" }}>Reminder List</h3>
                    <div className="flex items-center gap-2 w-full sm:w-auto min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <select
                        value={sortBy}
                        onChange={(e) => setSortBy(e.target.value as "NEWEST" | "OLDEST" | "PRIORITY" | "EXPIRY")}
                        className="flex-1 sm:flex-none px-3 py-1.5 text-sm rounded-lg outline-none min-w-0"
                        style={{ boxSizing: 'border-box', maxWidth: '100%', background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.14)', color: 'rgba(255,255,255,0.80)' }}
                        aria-label="Sort reminders by"
                        title="Sort reminders by"
                      >
                        <option value="NEWEST">Newest First</option>
                        <option value="OLDEST">Oldest First</option>
                        <option value="PRIORITY">Priority</option>
                        <option value="EXPIRY">Expiry Date</option>
                      </select>
                      <button
                        onClick={() => {
                          if (selectedDriver) loadDriverReminders(selectedDriver);
                          loadExpiringDocuments();
                        }}
                        className="px-3 py-1.5 text-sm rounded-lg transition-all flex items-center gap-2 whitespace-nowrap flex-shrink-0"
                        style={{ background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.65)', boxSizing: 'border-box' }}
                      >
                        <RefreshCw className="h-4 w-4" />
                        <span className="hidden sm:inline">Refresh</span>
                      </button>
                    </div>
                  </div>

                  {/* Search Bar & Results Count */}
                  <div className="mb-4 space-y-2 min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%', overflow: 'hidden' }}>
                    <div className="relative min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 pointer-events-none z-10" style={{ color: 'rgba(255,255,255,0.35)' }} />
                      <input
                        type="text"
                        placeholder="Search reminders by message, type, or action..."
                        value={reminderSearch}
                        onChange={(e) => setReminderSearch(e.target.value)}
                        className="w-full pl-10 pr-10 py-2.5 rounded-lg focus:outline-none transition-all"
                        style={{ boxSizing: 'border-box', maxWidth: '100%', background: 'rgba(255,255,255,0.07)', border: '1px solid rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.88)' }}
                      />
                      {reminderSearch && (
                        <button
                          onClick={() => setReminderSearch("")}
                          className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors z-10"
                          aria-label="Clear search"
                          title="Clear search"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 text-sm min-w-0" style={{ boxSizing: 'border-box', maxWidth: '100%' }}>
                      <span className="text-xs sm:text-sm" style={{ color: 'rgba(255,255,255,0.50)' }}>
                        Showing <span className="font-semibold" style={{ color: 'rgba(255,255,255,0.85)' }}>{filteredReminders.length}</span> of <span className="font-semibold" style={{ color: 'rgba(255,255,255,0.85)' }}>{reminderData.items.length}</span> reminders
                      </span>
                      {(activeFilters.length > 0 || reminderSearch) && (
                        <button
                          onClick={clearAllFilters}
                          className="font-medium flex items-center gap-1 text-xs sm:text-sm whitespace-nowrap"
                          style={{ color: '#6ee7b7' }}
                        >
                          <XCircle className="h-4 w-4" />
                          Clear Filters
                        </button>
                      )}
                    </div>
                  </div>
                  <div className="space-y-3 max-h-[500px] overflow-y-auto pr-2" style={{ boxSizing: 'border-box' }}>
                    {filteredReminders.length > 0 ? (
                      filteredReminders.map((reminder) => {
                        const Icon = getReminderIcon(reminder.type);
                        return (
                          <div
                            key={reminder.id}
                            className={`rounded-lg p-4 break-words ${
                              !reminder.isRead ? "ring-1 ring-offset-1" : ""
                            }`}
                            style={{
                              background: reminder.type === "ALERT" || reminder.type === "POLICY_VIOLATION" ? "rgba(239,68,68,0.13)" : reminder.type === "WARNING" ? "rgba(245,158,11,0.13)" : reminder.type === "LICENSE_EXPIRY" || reminder.type === "INSURANCE_EXPIRY" ? "rgba(139,92,246,0.13)" : reminder.type === "SAFETY" ? "rgba(245,158,11,0.10)" : "rgba(59,130,246,0.12)",
                              border: reminder.type === "ALERT" || reminder.type === "POLICY_VIOLATION" ? "1px solid rgba(239,68,68,0.30)" : reminder.type === "WARNING" ? "1px solid rgba(245,158,11,0.30)" : reminder.type === "LICENSE_EXPIRY" || reminder.type === "INSURANCE_EXPIRY" ? "1px solid rgba(139,92,246,0.30)" : reminder.type === "SAFETY" ? "1px solid rgba(245,158,11,0.25)" : "1px solid rgba(59,130,246,0.28)",
                              boxSizing: 'border-box', maxWidth: '100%', wordWrap: 'break-word'
                            }}
                          >
                            <div className="flex items-start gap-3">
                              <Icon className="h-5 w-5 flex-shrink-0 mt-0.5" style={{ color: reminder.type === "ALERT" || reminder.type === "POLICY_VIOLATION" ? "#fca5a5" : reminder.type === "WARNING" || reminder.type === "SAFETY" ? "#fcd34d" : reminder.type === "LICENSE_EXPIRY" || reminder.type === "INSURANCE_EXPIRY" ? "#c4b5fd" : "#93c5fd" }} />
                              <div className="flex-1">
                                <div className="flex items-center justify-between mb-1">
                                  <span className="text-xs font-medium uppercase" style={{ color: 'rgba(255,255,255,0.60)' }}>{reminder.type.replace('_', ' ')}</span>
                                  <div className="flex items-center gap-2">
                                    {!reminder.isRead && (
                                      <span className="px-2 py-0.5 bg-red-500 text-white text-xs rounded-full">New</span>
                                    )}
                                    {reminder.expiresAt && new Date(reminder.expiresAt) < new Date() && (
                                      <span className="px-2 py-0.5 bg-gray-500 text-white text-xs rounded-full">Expired</span>
                                    )}
                                  </div>
                                </div>
                                <p className="text-sm font-medium mb-1 break-words" style={{ color: 'rgba(255,255,255,0.90)', wordWrap: 'break-word', overflowWrap: 'break-word' }}>{reminder.message}</p>
                                {reminder.action && (
                                  <p className="text-xs mt-1" style={{ color: 'rgba(255,255,255,0.50)' }}>Action: {reminder.action}</p>
                                )}
                                {reminder.expiresAt && (
                                  <p className="text-xs mt-1" style={{ color: 'rgba(255,255,255,0.45)' }}>
                                    Expires: {new Date(reminder.expiresAt).toLocaleDateString()}
                                  </p>
                                )}
                                <p className="text-xs mt-2" style={{ color: 'rgba(255,255,255,0.35)' }}>
                                  {new Date(reminder.createdAt).toLocaleString()}
                                </p>
                              </div>
                            </div>
                          </div>
                        );
                      })
                    ) : (
                      <div className="text-center py-8">
                        <Bell className="h-12 w-12 mx-auto mb-3" style={{ color: 'rgba(255,255,255,0.20)' }} />
                        <p style={{ color: 'rgba(255,255,255,0.45)' }}>
                          {reminderData.items.length === 0 
                            ? "No reminders yet" 
                            : "No reminders match the selected filters"}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Goals Section */}
              <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Target className="h-5 w-5 text-emerald-600" />
                  <h3 className="text-lg font-semibold text-gray-900">Driver Goals & Tracking</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-blue-600" />
                      <span className="text-sm font-medium text-gray-700">Trips Goal</span>
                    </div>
                    <p className="text-2xl font-bold text-blue-600">-</p>
                    <p className="text-xs text-gray-500 mt-1">Set reminder goal for trips</p>
                  </div>
                  <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
                    <div className="flex items-center gap-2 mb-2">
                      <Target className="h-4 w-4 text-purple-600" />
                      <span className="text-sm font-medium text-gray-700">Earnings Goal</span>
                    </div>
                    <p className="text-2xl font-bold text-purple-600">-</p>
                    <p className="text-xs text-gray-500 mt-1">Set reminder goal for earnings</p>
                  </div>
                </div>
                <p className="text-xs text-gray-500 mt-4">
                  Goals can be set when creating reminders to track driver progress
                </p>
              </div>
            </div>
          ) : (
            <div style={{ background: "linear-gradient(135deg, #0a1a19 0%, #0d2320 60%, #0a1f2e 100%)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "1rem", boxShadow: "0 8px 32px rgba(0,0,0,0.45)", padding: "3rem", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
              <div style={{ width: 56, height: 56, borderRadius: "50%", background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.12)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "1rem" }}>
                <Bell style={{ width: 26, height: 26, color: "rgba(255,255,255,0.35)" }} />
              </div>
              <p style={{ color: "rgba(255,255,255,0.50)", fontSize: "0.9rem" }}>Select a driver to view their reminders</p>
            </div>
          )}
        </div>
      </div>

      {/* Create Reminder Modal */}
      {showCreateModal && selectedDriver && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" style={{ boxSizing: 'border-box' }}>
          <div className="bg-white rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto" style={{ boxSizing: 'border-box', width: '100%', maxWidth: '672px' }}>
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900">Create Reminder</h2>
              <button
                onClick={() => setShowCreateModal(false)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors flex-shrink-0"
                aria-label="Close modal"
                title="Close modal"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="space-y-4" style={{ boxSizing: 'border-box', width: '100%' }}>
              <div style={{ boxSizing: 'border-box', width: '100%' }}>
                <label className="block text-sm font-medium text-gray-700 mb-2">Reminder Type</label>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-2" style={{ boxSizing: 'border-box', width: '100%' }}>
                  {REMINDER_TYPES.map((type) => {
                    const Icon = type.icon;
                    return (
                      <button
                        key={type.value}
                        onClick={() => setReminderType(type.value)}
                        className={`p-3 rounded-lg border-2 transition-all text-left w-full ${
                          reminderType === type.value
                            ? "border-emerald-600 bg-emerald-50"
                            : "border-gray-200 hover:border-gray-300"
                        }`}
                        style={{ boxSizing: 'border-box', minWidth: 0 }}
                      >
                        <div className="flex items-center gap-2 mb-1">
                          <Icon className={`h-4 w-4 flex-shrink-0 ${reminderType === type.value ? "text-emerald-600" : "text-gray-600"}`} />
                          <span className={`text-sm font-medium truncate ${reminderType === type.value ? "text-emerald-700" : "text-gray-700"}`}>
                            {type.label}
                          </span>
                        </div>
                        <p className="text-xs text-gray-500 line-clamp-2">{type.description}</p>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div style={{ boxSizing: 'border-box', width: '100%' }}>
                <label className="block text-sm font-medium text-gray-700 mb-2">Message *</label>
                <textarea
                  value={reminderMessage}
                  onChange={(e) => setReminderMessage(e.target.value)}
                  placeholder="Enter reminder message..."
                  rows={4}
                  className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500 resize-none"
                  style={{ boxSizing: 'border-box', width: '100%' }}
                  required
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Action (Optional)</label>
                  <input
                    type="text"
                    value={reminderAction}
                    onChange={(e) => setReminderAction(e.target.value)}
                    placeholder="e.g., Renew License"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Action Link (Optional)</label>
                  <input
                    type="text"
                    value={reminderActionLink}
                    onChange={(e) => setReminderActionLink(e.target.value)}
                    placeholder="e.g., /driver/documents"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Expiration Date (Optional)</label>
                  <input
                    type="date"
                    value={reminderExpiresAt}
                    onChange={(e) => setReminderExpiresAt(e.target.value)}
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                    aria-label="Expiration Date (Optional)"
                    title="Expiration Date (Optional)"
                  />
                </div>
                <div style={{ boxSizing: 'border-box', width: '100%', minWidth: 0 }}>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Goal/Tracking (Optional)</label>
                  <input
                    type="text"
                    value={reminderGoal}
                    onChange={(e) => setReminderGoal(e.target.value)}
                    placeholder="e.g., Complete 50 trips this month"
                    className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
                    style={{ boxSizing: 'border-box', width: '100%' }}
                  />
                </div>
              </div>

              <div className="flex gap-3 pt-4" style={{ boxSizing: 'border-box', width: '100%' }}>
                <button
                  onClick={createReminder}
                  disabled={!reminderMessage.trim() || creating}
                  className="flex-1 px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  style={{ boxSizing: 'border-box', minWidth: 0 }}
                >
                  {creating ? "Creating..." : "Create Reminder"}
                </button>
                <button
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-all flex-shrink-0"
                  style={{ boxSizing: 'border-box' }}
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
